### ISSUE TITLE
core: history api support

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#113]
Make sure History API is enabled (was html5Mode with angularjs)

**Comment by SuperITMan** [comment]
Currently in the showcase/starter, we have the following code in `app.module.ts` file
```typescript
@NgModule({
  imports: [
    UIRouterModule.forRoot({
	states: APP_STATES,
	useHash: !Boolean(history.pushState),
	otherwise: "otherwise",
	config: routerConfigFn
    }),
  ]
})
```

According to the UIRouter documentation for useHash, we already have **History API** enabled. 
`history.pushState(history.pushState)` is returning `false` when we execute it in Chrome. That means we are using [`PathLocationStrategy`](https://angular.io/docs/ts/latest/api/common/index/PathLocationStrategy-class.html) from Angular.

See :
```js
/**
 * Chooses a `LocationStrategy`.
 *
 * The location strategy enables either HTML5 Push State
 * (Requires server-side support) or "HashBang" URLs.
 *
 * When `false`, uses [`PathLocationStrategy`](https://angular.io/docs/ts/latest/api/common/index/PathLocationStrategy-class.html)
 * When `true`, uses [`HashLocationStrategy`](https://angular.io/docs/ts/latest/api/common/index/HashLocationStrategy-class.html)
 *
 * Defaults to `false`
 */
```

@christophercr Do you remember why we execute `!Boolean(history.pushState)` ?

**Comment by christophercr** [comment]
As far as I remember, the reason why we put `useHash: !Boolean(history.pushState),` was simply to consider browsers that do not support HTML5 Push State such as IE older than 10.

But I don't think that's relevant anymore since we just care about IE 11.

So I will create a PR to change this to `useHash: false,` so it is clear that we support the HTML5 push state 😉
