### ISSUE TITLE
config: create new package to share our code style configurations

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1196]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

If a developer wants to use our configuration for:
  * prettier
  * tslint
  * typescript
  * stylelint
  
He has to install `stark-build` with lots of dependencies he maybe does not need.

## Expected behavior

We should share all our configurations files, currently only but could be increased, in a new stark package. 

Configuration files should not be linked to stark-build.

Now, the big question is: which name should we use for this new package ?
@cnomes @christophercr @dsebastien please don't hesitate to share your ideas 😃 

I suggest `stark-config`

**Comment by cnomes** [comment]
Does it still make a lot of sense to keep the `stark-build` package if we do this?

**Comment by SuperITMan** [comment]
For the build itself, it makes sense.
We still have our webpack stuff and all the dependencies to install thanks to stark-build.

**Comment by cnomes** [comment]
Well, most of the webpack stuff is also "config" and then maybe we could move the dependencies to showcase / starter

**Comment by christophercr** [comment]
Mmm IMO we should keep `stark-build` because it is something completely different than "configuration":

- `stark-build`: provides the necessary Angular build configuration (although it is really minimal) to build correctly any Stark based app, therefore we cannot remove it, it is an essential part of Stark, without it, stark-core and stark-ui simply won't work.
- `stark-config` (although I would prefer something like `stark-code-style`): it would be a package where we will provide some configs for the code style tooling we use like TsLint, SonarTS, Stylelint, Codelyzer. So this package is not essential at all, it should not affect any package at all.

Thinking a bit more on this, we should see where are we going to put the Stylelint config... because that is something extra we use in our build... so I guess it should be in `stark-build` instead...

**Comment by SuperITMan** [comment]
@christophercr I agree with you. Also, as I said before `stark-build` manages the dependencies, as `@angular/cli` does. We should keep it as it is 😊 

What I suggest for the new package is:
  * `stark-build` :
    * package.json - same dependencies as we have now
    * config/
      * build-utils.js
      * empty.js
      * helpers.js
      * json-server.common.js
      * ng-cli-utils.js
      * webpack.common-data.js
      * webpack-partial.common.js
      * webpack-partial.dev.js
      * webpack-partial.prod.js
    * typings/*
    
  
  * `stark-config` (or `stark-code-style` or whatever):
    * .prettierrc.js
    * stylelint.config.js
    * tslint.js
    * tsconfig.json
	
  * Files to move in the showcase:
    * config/github-deploy/index.js
    * config/webpack.github-deploy.js

What do you think about this ? 😊

**Comment by cnomes** [comment]
Or maybe `@nationalbankbelgium/code-style` because it would be usable outside of Stark?

**Comment by christophercr** [comment]
Package created: https://github.com/NationalBankBelgium/code-style 👍

**Comment by christophercr** [comment]
The new package is now used in the Stark packages, the Starter and Showcase thanks to #1295
