### ISSUE TITLE
ui: angular material customizations

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#124]
Integrate our customizations for default settings:
* [ ] first day of week
* [ ] date format
* [ ] date parsing

**Comment by christophercr** [comment]
Now, with Angular Material, the Date parsing/formatting customizations should be done providing a `MAT_DATE_FORMATS` as follows:

```
providers: [{ provide: MAT_DATE_FORMATS, useValue: CUSTOM_FORMATS_CONSTANT }
```

Stark provides some formats in a `STARK_DATE_FORMATS` constant that the developer can provide if he wants or he can provide his own formats in another constant.

As for the "first day of week" setting, since we use Moment dates, this is done automatically by the `MomentDateAdapter` included as part of the `MomentDateModule` that is used in the `StarkDatePicker` component
