### ISSUE TITLE
ui: session - dropdown/menu opened in header are not closed when user is logged out

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1570]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When the session is closed by the StarkSession service, it redirects to the session-logout page.
Unfortunately, if the user opened the language selector before being logged out, it stays opened.

![image](https://user-images.githubusercontent.com/10333565/72900054-1b542000-3d1f-11ea-8eee-208168e484a5.png)

## Expected behavior

The dropdown should be closed when the user is redirected to the session-logout page.

## Minimal reproduction of the problem with instructions

Open the language-selector and wait until you are logged out automatically.

## What is the motivation / use case for changing the behavior?

Bug fixing.

## Environment

<pre><code>
Angular version: 7.x
Stark version: 10.0.0-rc.3

</code></pre>

**Comment by christophercr** [comment]
After investigating the issue, it turns out the cause of the problem is that any Angular Material element that creates an overlay, such as the `mat-select` inside the `StarkDropdown` component, is embedded in an [`OverlayContainer`](https://v7.material.angular.io/cdk/overlay/api#OverlayContainer) and this container is not placed inside the `app` component but at the root of the page.

Therefore, when the view is destroyed by the router when navigating to the `SessionExpiredPage`, the container remains there with the overlays that it had at the moment (open or closed):

<img width="1008" alt="Screenshot 2020-03-24 at 10 43 12" src="https://user-images.githubusercontent.com/5698318/77411219-5a086400-6dbc-11ea-97c1-b15f6f8122ae.png">


So, the solution would be then to destroy such `OverlayContainer` when navigating to any of the `exit` states: `SessionExpired` and `SessionLogout`. This can be done by calling its [`ngOnDestroy`](https://v7.material.angular.io/cdk/overlay/api#OverlayContainer) method.
