### ISSUE TITLE
build: add webpack monitor

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#322]
Goal: provide a way to quickly know about the bundle/dependencies size: https://www.npmjs.com/package/source-map-explorer

**Comment by tenretC** [comment]
The name of our bundles in the starter are never the same, so we cannot use this package because we have to specify the bundle name to run the source-map-explorer script.

We have 2 alternatives :

- [webpackmonitor](https://github.com/webpackmonitor/webpackmonitor)

- [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer)
