### ISSUE TITLE
admin: configure greenkeeper

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#352]
Goal: ease updating of libraries by adding greenkeeper: https://greenkeeper.io/ (https://github.com/greenkeeperio/greenkeeper)

* [x] add greenkeeper
* [x] add https://github.com/greenkeeperio/greenkeeper-lockfile (necessary for monorepos)
* [x] configure greenkeeper.json

**Comment by dsebastien** [comment]
Quickly tried to configure GK, but it seems a bit optimistic by default, we need to configure the libraries it should not touch (like typescript, angular, ...) :)

https://github.com/NationalBankBelgium/stark/pull/399/files

**Comment by dsebastien** [comment]
Related PR: #399. Kept on hold for now given issue mentioned in the comment above..

**Comment by christophercr** [comment]
I've updated the PR #399 to modify the 'greenkeeper.json' in order to ignore some packages we shouldn't upgrade as @dsebastien mentioned:

- @types/node (we use node 8 so we can't use the latest types which are for node 10)
- class-validator (latest version has breaking changes that we should manually fix)
- typescript (we should stay in v2.7.2 due to Angular)
- tslint-sonarts (latest version has some bugs)

**Comment by christophercr** [comment]
Closed in #399
