### ISSUE TITLE
build: prod build broken

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
When executing `npm run build:prod` in the starter or showcase we get errors about "cacheGroups" (does not exist in the schema).

Also those warnings:

```
 10% building modules 0/1 modules 1 active …stark\showcase\src\polyfills.browser.tsWarning: The 'no-accessor-field-mismatch' rule requires type information.
Warning: The 'no-array-delete' rule requires type information.
Warning: The 'no-collection-size-mischeck' rule requires type information.
Warning: The 'no-dead-store' rule requires type information.
Warning: The 'no-element-overwrite' rule requires type information.
Warning: The 'no-gratuitous-expressions' rule requires type information.
Warning: The 'no-ignored-initial-value' rule requires type information.
Warning: The 'no-ignored-return' rule requires type information.
Warning: The 'no-misleading-array-reverse' rule requires type information.
Warning: The 'no-redundant-boolean' rule requires type information.
Warning: The 'no-return-type-any' rule requires type information.
Warning: The 'no-self-assignment' rule requires type information.
Warning: The 'no-unused-array' rule requires type information.
Warning: The 'no-use-of-empty-return-value' rule requires type information.
Warning: The 'no-useless-cast' rule requires type information.
Warning: The 'no-useless-intersection' rule requires type information.
Warning: The 'no-variable-usage-before-declaration' rule requires type information.
Warning: The 'parameters-max-number' rule requires type information.
Warning: The 'prefer-immediate-return' rule requires type information.
Warning: The 'use-type-alias' rule requires type information.
```

## Expected behavior
No errors or warnings :)

For Tooling issues:
- Node version: 8.7.0
- Platform:  Win

**Comment by christophercr** [comment]
The issue about the lint warnings: `Warning: The 'no-array-delete' rule requires type information` are because there are some rules in TSLint enabled which previously (before TsLint v5.9.0) required a special flag to be executed.

Now that those rules are enabled, it seems that `ts-loader` is not executing them correctly because according to the loader the flag to enable the type information is missing. To enable such flag the `typeCheck` option in the `ts-loader` should be set to true but unfortunately that has a big performance impact in the build: wbuchwalter/tslint-loader#76 which was already addresed by this PR wbuchwalter/tslint-loader#78 but it has be opened for almost a year!

So we need to find a solution for this, which might be to switch to the [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) as it is mentioned in [wbuchwalter/tslint-loader#78](https://github.com/wbuchwalter/tslint-loader/pull/78#issuecomment-339418463)... for example: https://github.com/TypeStrong/ts-loader/blob/master/examples/fork-ts-checker/webpack.config.js
