### ISSUE TITLE
ui: dialogs - implement re-usable Angular Material dialog components

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#793]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior
We should integrate the dialog component that we had in the previous Stark release, unless its feature set can be covered fully by Angular Material..

**Comment by christophercr** [comment]
As discussed with @SuperITMan, this feature is provided by Angular Material so we won't re-implement such feature in Stark 10.

However we could still provide a preset of Dialog components like we did before: confirm, alert and prompt so the developer can re-use them if he wants to instead of duplicating code every time and along different apps.

**Comment by dsebastien** [comment]
+1
