### ISSUE TITLE
core: add support for RxDB

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#89]
Goal: investigate RxDB (https://github.com/pubkey/rxdb)

**Comment by christophercr** [comment]
As discussed, we won't integrate RXDB since it is more an ORM which would require a lot of work on our side and we just need a solution for mocking backends where it is not possible to have a separate NodeJs process (i.e. the Starter on GitHub pages).

Therefore, we will use the [in-memory-web-api](https://github.com/angular/in-memory-web-api) library provided by Angular which provides everything we need, it is easier to implement and we can re-use some common logic from our JSON-Server integration.
