### ISSUE TITLE
core: http

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#96]
Add support for NBB's REST design guide with our http api on top of NG5+'s http service
Keep our current model with cerialize.

Should be a dedicated sub-package and module in stark-core

Ref: https://angular.io/guide/http

**Comment by dsebastien** [comment]
blocked by #73

**Comment by christophercr** [comment]
Just to let you know that currently the build of stark-core fails due to these 2 errors:

- the compilation of TS files with decorators from `cerialize` and `class-validator` fails because of this issue https://github.com/angular/angular-cli/issues/8434 so I'm looking at this to see if we can upgrade the angular/cli version.

- the Angular compilar (ngc) throws lots of errors due to the redundant JSDocs we have in some of our classes (see https://github.com/angular/angular/issues/19969). So I have fixed these issues in [this commit](https://github.com/christophercr/stark/commit/1e8a6cf16b77f607eef8dd7af58286cf6a72cfea) in my fork.
